apiVersion: v1
kind: Pod
metadata:
  name: conversaotemperatura
  labels:
    name: conversaotemperatura
spec:
  containers:
  - name: conversaotemperatura
    image: rodrigoclemente/conversao-temperatura:1.0.0
    ports:
      - containerPort: 8080
